version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - app-network

  backend:
    build: ./Backend
    container_name: express-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=my_database
    networks:
      - app-network

  db:
    build: ./DB
    container_name: postgres-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_database
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge