version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: react-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    networks:
      - app-network

  backend:
    build: ./Backend
    container_name: express-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL: postgresql://postgres:postgres@db:5432/my_database
    networks:
      - app-network

  db:
    build: ./DB
    container_name: postgres-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_database
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge